apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-demo-sql
  name: service2-ms-demo-sql
  namespace: ms-demo-sql
spec:
  selector:
    app: ms-demo-sql
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433